### ISSUE TITLE
OHLCVol Resampling/Trading Logic ouside tick_event?

### ISSUE THREAD

**Issue by SergeGardien** [jamesmawm/Mastering-Python-for-Finance-source-codes#1]
Hi James,
I'm using your [AlgoSystem.py](https://github.com/jamesmawm/Mastering-Python-for-Finance-source-codes/blob/master/B03898_08_codes/AlgoSystem.py) to build the infrastructure for my trading system (paired with a forecasting model). 

My model requires OHLC+Volume data sampled at 1min freq (I could potentially use other sampling freq. too) but Interactive Brokers only provides 5sec Real Time Bars ([reqRealTimeBars](https://www.interactivebrokers.com/en/software/api/apiguide/java/reqrealtimebars.htm)) so I prefer to use [reqMktData](https://www.interactivebrokers.com/en/software/api/apiguide/java/reqmktdata.htm) and build the OHLCV data by myself.

Wouldn't it be better to put the OHLCV calc and the trading logic outside the [tick_event method](https://github.com/jamesmawm/Mastering-Python-for-Finance-source-codes/blob/master/B03898_08_codes/AlgoSystem.py#L53)?

I'm thinking of putting the OHLCV calc in [start](https://github.com/jamesmawm/Mastering-Python-for-Finance-source-codes/blob/master/B03898_08_codes/AlgoSystem.py#L183) with something like (pseudocode):

```
self.register_callback_functions()
set OHLCV_1m_time_counter_start
self.request_market_data(self.symbol_id, self.symbol)
set OHLCV_1m_time_counter_end
if OHLCV_1m_time_counter_end - OHLCV_1m_time_counter_start = 1min
    calculate OHLCV()
    perform_trade_logic()
```

What do you think?

**Comment by jamesmawm** [comment]
self.request_market_data only sends a command to the server.  During this period between the command is sent and receipt of the first tick data may have significant delay. Wrapping this with counter `start` and `end` doesn't account for this delay accurately, and only run once.

Perhaps a better way would be to use threads running at 60 secs interval like:
`threading.Timer(60.0, calculate_ohlv_and_perform_trade_logic).start()`

Depending on how busy your CPU is, your intervals might go off course but it should do the job fair enough. Putting the trading logic outside the `tick_event_method` is fine as long as you know what you're doing :)

**Comment by SergeGardien** [comment]
Using Timer seems a good idea. I'll try it out.

Regarding the trading logic, I'm putting it outside tick_event_method because it requires 1min OHLC data (that's the highest freq. I can use to beat transaction costs if I use market instead of limit orders). I could also do some more HFT stuffs by passing non-periodic tick data and in that case I would put the trading logic inside tick_event_method so it can react soon as I get the data.

Many thanks for the advices :)
