### ISSUE TITLE
Syntax error/unsupported Operand for Vasicek Python

### ISSUE THREAD

**Issue by kiann00** [jamesmawm/Mastering-Python-for-Finance-source-codes#2]
Hi James, I got your book as a reference for utilizing python in pricing financial modules.

I was trying to test/implement your set-up for Vasicek model : B03898_05_Codes/VasicekCZCB.py. However, when I run it under my python (3.4) shell, I get the following error below.

Would you know what is causing the issue?

Kind regards

Traceback (most recent call last):
  File "<pyshell#21>", line 1, in <module>
    r, vals = Vasicek.vasicek_czcb_values(r0, R, ratio, 1.0, sigma, kappa, theta, M, prob, max_policy_iter, grid_struct_interval, rs)
  File "C:\Python34\lib\py_Vasicek.py", line 17, in vasicek_czcb_values
    r_min, dr, N, dtau = self.vasicek_params(r0, M, sigma, kappa, theta, T, prob, grid_struct_const, rs)
  File "C:\Python34\lib\py_Vasicek.py", line 32, in vasicek_params
    N = self.calculate_N/(grid_struct_const, dt, sigma, r_max, r_min)
TypeError: unsupported operand type(s) for /: 'method' and 'tuple'

**Comment by jamesmawm** [comment]
You have an unnecessary `/` in the line `N = self.calculate_N/(grid_struct_const, dt, sigma, r_max, r_min)`.
